### ISSUE TITLE
您好，为什末这车牌的置信度这么低

### ISSUE THREAD

**Issue by oftenliu** [zeusees/Mobilenet-SSD-License-Plate-Detection#10]

**Comment by lsy17096535** [comment]
有可能训练数据不够充分

**Comment by oftenliu** [comment]
ccpd数据集不是有几十万张吗？　另外，您在训练时，anchor　box的数量和正负样本的比例调整吗

**Comment by lsy17096535** [comment]
当时没有用ccpd训练，正负样本比例没有调整

**Comment by oftenliu** [comment]
oo,感谢大佬回复！！

**Comment by oftenliu** [comment]
大佬，请问下你这边训练时，类别是2吗，我训练后，loss收敛到1左右，但测试时车牌的置信度0.01级？

**Comment by oftenliu** [comment]
另外，不知道你训练时设置样本的阈值和正负样本的比例，loss权重可否告知下

**Comment by lsy17096535** [comment]
lr=0.0001 finetune
